name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch: # Allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: NeonStack
          outputs: |
            dist/github-snake.svg

      - name: Upload Snake to GitHub
        run: |
          mkdir -p assets
          mv dist/github-snake.svg assets/
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/github-snake.svg
          git commit -m "Generated GitHub Snake"
          git push
